name: "EXPERIMENTAL TEST Build"
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Node.js and npm
        uses: actions/setup-node@v6
        with:
          node-version: '24.11.1'
          package-manager-cache: false

      - name: Update npm environent
        run: npm install

      - name: Compile TypeScript scripts
        run: npm run build-tsc

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: npm run build-win

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build-linux

      - name: Build for Mac
        if: matrix.os == 'macos-latest'
        run: npm run build-mac

      - name: Upload Windows Artifacts
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v5
        with:
          name: artifacts_windows
          path: |
            ./dist/*.exe
            ./dist/*.blockmap
            ./dist/latest.yml
          retention-days: 1

      - name: Upload Linux Artifacts
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v5
        with:
          name: artifacts_linux
          path: |
            ./dist/*.deb
            ./dist/*.AppImage
            ./dist/latest-linux.yml
          retention-days: 1

      - name: Upload Mac Artifacts
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v5
        with:
          name: artifacts_macos
          path: |
            ./dist/*.dmg
            ./dist/*.blockmap
            ./dist/*.zip
            ./dist/latest-mac.yml
          retention-days: 1
