name: "Release-Linux"
on:
  release:
    types: ["published"]

jobs:
  publish:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - name: Wait for package update
      uses: ivan-sre/action-wait-for-check@v5.0.0
      id: wait-for-commit
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: update
        ref: ${{ github.event.pull_request.head.sha || github.sha }}

    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        ref: "main"

    - name: Make Release Changes
      run: . .github/release-changes.sh "${{ github.event.release.tag_name }}"

    - name: Install Node.js and npm
      uses: actions/setup-node@v6
      with:
        node-version: '24.11.1'
        package-manager-cache: false

    - name: Update npm
      run: npm install

    - name: Compile TypeScript Scripts
      run: npm run build-tsc

    - name: Build for Linux
      run: npm run build-linux

    - name: Rename Deb File
      run: mv ./dist/*.deb ./dist/CPZero-Client-${{ env.version }}.deb
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v5
      with:
        name: artifacts_linux
        path: |
          ./dist/*.deb
          ./dist/*.AppImage
          ./dist/latest-linux.yml

    - name: "Upload Artifacts to Release"
      uses: "ncipollo/release-action@v1.20.0"
      with:
        allowUpdates: true
        artifactErrorsFailBuild: true
        artifacts: "dist/*.deb,dist/*.AppImage,dist/latest-linux.yml"
        token: ${{ secrets.GITHUB_TOKEN }}
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
