name: "Release-MacOS"
on:
  release:
    types: ["published"]

jobs:
  publish:
    permissions: write-all
    runs-on: macos-latest

    steps:
    - name: Wait for package update
      uses: ivan-sre/action-wait-for-check@v5.0.0
      id: wait-for-commit
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: update
        ref: ${{ github.event.pull_request.head.sha || github.sha }}

    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        ref: "main"

    - name: Install Node.js and npm
      uses: actions/setup-node@v6
      with:
        node-version: '24.11.1'
        package-manager-cache: false

    - name: Update npm environent
      run: npm install

    - name: Compile TypeScript scripts
      run: npm run build-tsc

    - name: Build for MacOS
      run: npm run build-mac
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v5
      with:
        name: artifacts_macos
        path: |
          ./dist/*.dmg
          ./dist/*.blockmap
          ./dist/*.zip
          ./dist/latest-mac.yml

    - name: "Upload Artifacts to Release"
      uses: "ncipollo/release-action@v1.20.0"
      with:
        allowUpdates: true
        artifactErrorsFailBuild: true
        artifacts: "dist/*.dmg,dist/*.blockmap,dist/*.zip,dist/latest-mac.yml"
        token: ${{ secrets.GITHUB_TOKEN }}
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
